version: '2'
services:
  bazarshop-app:
    image: bazarshop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bazarshop-postgresql:5432/bazarshop
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bazarshop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bazarshop-elasticsearch:9200
    ports:
      - 8080:8080
  bazarshop-postgresql:
    extends:
      file: postgresql.yml
      service: bazarshop-postgresql
  bazarshop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bazarshop-elasticsearch
